name: Python Package

on:
  push:
    tags:
      - 'v*.*.*' 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel  # Install wheel explicitly

      - name: Build and package the release
        run: |
          python setup.py sdist bdist_wheel


      - name: Build and package the release
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload release assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

      - name: Publish to PyPI (optional)
        if: github.ref == 'refs/tags/v*.*.*'
        run: |
          python -m pip install --upgrade setuptools wheel twine
          twine upload dist/* -u ${{secrets.PYPI_USERNAME}} -p ${{secrets.PYPI_PASSWORD}}
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
