name: Python Package

on:
  push:
    tags:
      - 'v*'  # Trigger workflow on tags like v1.0.0, v1.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel  # Install wheel explicitly

      - name: Build and package the release
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload release assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install --upgrade setuptools wheel twine
          twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
